/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.ui;

import fr.inria.diverse.ui.AbstractNetworkModelTestUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class NetworkModelTestUiModule extends AbstractNetworkModelTestUiModule {
  public NetworkModelTestUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
