/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.validation;

import fr.inria.diverse.validation.AbstractNetworkModelTestValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class NetworkModelTestValidator extends AbstractNetworkModelTestValidator {
}
