/*
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.ui.tests;

import com.google.inject.Injector;
import fr.inria.diverse.newtorkmodeltest.ui.internal.NewtorkmodeltestActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class NetworkModelTestUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return NewtorkmodeltestActivator.getInstance().getInjector("fr.inria.diverse.NetworkModelTest");
	}

}
