/*
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class NetworkModelTestRuntimeModule extends AbstractNetworkModelTestRuntimeModule {
}
