/*
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class NetworkModelTestStandaloneSetup extends NetworkModelTestStandaloneSetupGenerated {

	def static void doSetup() {
		new NetworkModelTestStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
