/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse;

import fr.inria.diverse.AbstractNetworkModelTestRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class NetworkModelTestRuntimeModule extends AbstractNetworkModelTestRuntimeModule {
}
