/*
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.parser.antlr;

import com.google.inject.Inject;
import fr.inria.diverse.parser.antlr.internal.InternalNetworkModelTestParser;
import fr.inria.diverse.services.NetworkModelTestGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class NetworkModelTestParser extends AbstractAntlrParser {

	@Inject
	private NetworkModelTestGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalNetworkModelTestParser createParser(XtextTokenStream stream) {
		return new InternalNetworkModelTestParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public NetworkModelTestGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(NetworkModelTestGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
