/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.inria.diverse.NetworkModelTestRuntimeModule;
import fr.inria.diverse.NetworkModelTestStandaloneSetup;
import fr.inria.diverse.ide.NetworkModelTestIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class NetworkModelTestIdeSetup extends NetworkModelTestStandaloneSetup {
  @Override
  public Injector createInjector() {
    NetworkModelTestRuntimeModule _networkModelTestRuntimeModule = new NetworkModelTestRuntimeModule();
    NetworkModelTestIdeModule _networkModelTestIdeModule = new NetworkModelTestIdeModule();
    return Guice.createInjector(Modules2.mixin(_networkModelTestRuntimeModule, _networkModelTestIdeModule));
  }
}
