/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.ide;

import fr.inria.diverse.ide.AbstractNetworkModelTestIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class NetworkModelTestIdeModule extends AbstractNetworkModelTestIdeModule {
}
