/*
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.tests

import com.google.inject.Inject
import fr.inria.diverse.networkModelTest.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.eclipse.xtext.util.EmfFormatter
import fr.inria.diverse.NetworkModelTestStandaloneSetup

@ExtendWith(InjectionExtension)
@InjectWith(NetworkModelTestInjectorProvider)
class NetworkModelTestParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
				config ConfigLvl1{
					OVS nodeOVS1{
						name: "Openvswitchmanagement-3"
						nodeID: "7508c161-e3c3-4e6d-8004-0ae0f2b7c7f6"
						eth0.IP: "192.168.1.11"
					}
					Docker nodeDockerUbuntu1{
						image: "UbuntuGuest"
						name: "DockerUbuntuGuest-5 (ODL Controller)"
						nodeID: "56fb43ab-3e2e-463e-9dd1-cbf109d3e9c3"
						eth0.IP: "192.168.1.12"
					}
					Firefox nodeFirefox1{
						name: "Firefox31.1.1~2.1"
						nodeID: "0450804c-738c-4e88-9dff-cb5f9eb5505f"
						eth0.IP: "192.168.1.13"
					}
					Docker nodeDockerUbuntu2{
						image: "UbuntuGuest"
						name: "DockerUbuntuGuest-1 (OFM Manager)"
						nodeID: "c2aaf06a-7afe-4779-a6ee-8b9c60602a4d"
						eth0.IP: "192.168.1.15"
					}
					EthSwitch nodeEthSwitch1{
						name: "EthernetSwitch-1"
						nodeID: "b6672b1b-3c0b-4362-b6cc-976aa133510d"
						eth0.IP: "192.168.1.16"
					}
					Docker nodeDockerUbuntu3{
						image: "UbuntuGuest"
						name: "UbuntuDockerGuest-2"
						nodeID: "3cc6d285-fa1d-430e-a36d-bd4bb908e1d6"
						eth0.IP: "192.168.1.17"
					}
					OVS nodeOVS2{
						name: "Openvswitchmanagement-1"
						nodeID: "aba2dc9a-c430-4fbc-8a81-470d6e19d852"
						eth0.IP: "192.168.1.18"
					}
					OVS nodeOVS3{
						name: "Openvswitchmanagement-2"
						nodeID: "64090bd4-155f-4272-8f0a-468e9cc349ee"
						eth0.IP: "192.168.1.19"
					}
					OVS nodeOVS4{
						name: "Openvswitchmanagement-4"
						nodeID: "38786aef-c1e6-4ca8-886f-079c6ec5fc89"
						eth0.IP: "192.168.1.20"
					}
					OVS nodeOVS5{
						name: "Openvswitchmanagement-5"
						nodeID: "fd3525d9-e92a-487d-a915-0adfe2c8a481"
						eth0.IP: "192.168.1.21"
					}
					Docker nodeDockerUbuntu2{
						image: "UbuntuGuest"
						name: "DockerUbuntuGuest-3"
						nodeID: "9c08391b-8295-4dfb-b290-d20b978e9931"
						eth0.IP: "192.168.1.22"
					}
					Docker nodeDockerUbuntu3{
						image: "UbuntuGuest"
						name: "DockerUbuntuGuest-8"
						nodeID: "335efc50-2f70-41a4-bfdd-3b02602e2c1b"
						eth0.IP: "192.168.1.23"
					}
					Docker nodeDockerUbuntu4{
						image: "UbuntuGuest"
						name: "DockerUbuntuGuest-9"
						nodeID: "3b565de2-571a-4099-ab15-b9440ac5f2a0"
						eth0.IP: "192.168.1.24"
					}
					Docker nodeDockerUbuntu5{
						image: "UbuntuGuest"
						name: "DockerUbuntuGuest-7"
						nodeID: "7926dc3c-cc6f-464a-9541-32b4bfd329d0"
						eth0.IP: "192.168.1.25"
					}
					Docker nodeDockerUbuntu6{
						image: "UbuntuGuest"
						name: "DockerUbuntuGuest-6"
						nodeID: "6628856d-6570-4bfb-96a5-8207ba0636be"
						eth0.IP: "192.168.1.26"
					}
					Docker nodeDockerUbuntu7{
						image: "UbuntuGuest"
						name: "DockerUbuntuGuest-10"
						nodeID: "50c207d0-090b-4892-9a83-2b5caf697742"
						eth0.IP: "192.168.1.27"
					}
					Docker nodeDockerUbuntu8{
						image: "UbuntuGuest"
						name: "DockerUbuntuGuest-11"
						nodeID: "83946d48-8e4b-4ac4-a4ac-adfc494f8783"
						eth0.IP: "192.168.1.28"
					}
					Docker nodeDockerUbuntu9{
						image: "UbuntuGuest"
						name: "DockerUbuntuGuest-4"
						nodeID: "063d29b5-c1da-473b-a61a-6a18f55e458b"
						eth0.IP: "192.168.1.29"
					}
					UbuntuDesktop nodeVideoServer{
						name: "UbuntuDesktopGuest16.04.5-2"
						nodeID: "cc874ac9-16b0-456a-acc4-32ff12125dc8"
						eth0.IP: "192.168.1.30"
					}
					UbuntuDesktop nodeVideoClient{
						name: "UbuntuDesktopGuest16.04.5-1"
						nodeID: "34b4c0d8-c6af-4624-b3e7-71db86ada775"
						eth0.IP: "192.168.1.31"
					}
					NAT nodeNAT1{
						name: "NAT-1"
						nodeID: "c4c28b31-3cc0-4703-8716-f0a2b2adeb38"
					}
					NAT nodeNAT2{
						name: "NAT-2"
						nodeID: "7255276c-8ff4-48c3-8268-6998b37a330a"
					}
					NAT nodeNAT3{
						name: "NAT-3"
						nodeID: "e464c182-039f-4b9b-9bbf-3786c2f2f92d"
					}
					bind nodeOVS1.eth5 and nodeDockerUbuntu1.eth0 linkID: "98185da1-7c1b-4dae-9311-7789a68d24c1"
									bind nodeOVS1.eth2 and nodeFirefox1.e0 linkID: "1fe6df82-4464-4935-a93e-a14b91733c69"
									bind nodeOVS1.eth3 and nodeEthSwitch1.e0 linkID: "9c6de63a-df38-4d9b-8bd3-2314e2b826d0"
									bind nodeOVS1.eth4 and nodeDockerUbuntu2.eth0 linkID: "897f9993-018a-4817-a229-ab5a3a50a769"
									bind nodeEthSwitch1.e2 and nodeNAT1.nat0 linkID: "fcea4ae0-784e-454e-9fa9-d4120f577ba6"
									bind nodeEthSwitch1.e6 and nodeOVS5.eth1 linkID: "349694ae-1f3c-4a11-ba1e-ec1c33b85c88"
									bind nodeEthSwitch1.e5 and nodeOVS4.eth1 linkID: "c8a0f51f-ec4a-4ed2-8f48-59e09822fbf1"
									bind nodeEthSwitch1.e4 and nodeOVS3.eth1 linkID: "fbeb1cca-980f-4381-aac2-e28e3759e950"
									bind nodeEthSwitch1.e3 and nodeOVS2.eth1 linkID: "168778a8-84f9-45cb-9ee8-a31868fd3b44"
									bind nodeEthSwitch1.e1 and nodeDockerUbuntu3.eth0 linkID: "141822b8-0e61-447a-a3e6-ad7fdee6b755"
									bind nodeOVS2.eth7 and nodeOVS5.eth2 linkID: "a7dab595-02ac-4d5a-946f-ff38b714005f"
									bind nodeOVS2.eth5 and nodeOVS4.eth6 linkID: "3d92c5ad-ed30-4c30-b7dc-dbbae71647b1"
									bind nodeOVS2.eth6 and nodeOVS3.eth4 linkID: "bb8dfba3-b160-4471-b940-d6d2b3ec1930"
									bind nodeOVS2.eth4 and nodeDockerUbuntu3.eth0 linkID: "69b62099-71f2-4adb-b4f5-60ad1f4170a6"
									bind nodeOVS2.eth3 and nodeDockerUbuntu2.eth0 linkID: "240d94a3-fd28-4a20-b91b-c6193a86aee0"
									bind nodeOVS2.eth2 and nodeVideoServer.eth0 linkID: "7d3396e6-7447-4b63-bdef-4d383eb113f5"
									bind nodeOVS3.eth7 and nodeNAT2.nat0 linkID: "93190686-5826-4672-83ac-421d483f69d0"
									bind nodeOVS3.eth6 and nodeOVS5.eth6 linkID: "45bd967f-f9bc-456d-bfe2-e83c1d59f7b5"
									bind nodeOVS3.eth5 and nodeOVS4.eth4 linkID: "d0ba44e4-36f2-4601-b39d-3563bbe8fd90"
									bind nodeOVS3.eth3 and nodeDockerUbuntu5.eth0 linkID: "a8f01ff6-8033-461f-aefd-76c0a5f7d4b6"
									bind nodeOVS3.eth2 and nodeDockerUbuntu4.eth0 linkID: "379c4382-b935-48fd-8fbb-8e925b11798a"
									bind nodeOVS4.eth7 and nodeNAT3.nat0 linkID: "53783b1b-0c4e-4bdf-a933-74daa68f533b"
									bind nodeOVS4.eth5 and nodeOVS5.eth5 linkID: "3a797621-3ac3-4326-9f36-5466753a3af5"
									bind nodeOVS4.eth3 and nodeDockerUbuntu7.eth0 linkID: "b6b344db-9f1c-44ca-a774-41010cc6fe9b"
									bind nodeOVS4.eth2 and nodeDockerUbuntu6.eth0 linkID: "991b16e0-2048-42c7-b8a4-61380b3afb40"
									bind nodeOVS5.eth4 and nodeDockerUbuntu9.eth0 linkID: "c3af3af2-29b1-4b97-9785-587f3e2d3e18"
									bind nodeOVS5.eth3 and nodeVideoClient.eth0 linkID: "20020843-9538-4e0c-98ce-8af19e68d56c"
									bind nodeOVS5.eth2 and nodeDockerUbuntu8.eth0 linkID: "5d7630ca-7428-4638-87f8-0a1b0efd1b43"
				}
		''')
		//var model = NetworkModelTestStandaloneSetup().
		println(EmfFormatter.objToStr(result))
		
		//validator.assertNoErrors(result)
		//val fsa = new InMemoryFileSystemAccess
		//generator.doGenerate(result.eResource, fsa)
		//fsa.allFiles.values.head.toString.contain('''''')
		
		//Assertions.assertNotNull(result)
		//val errors = result.eResource.errors
		//Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

	}
}
