/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.networkModelTest;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Binding</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.networkModelTest.Binding#getNodeA <em>Node A</em>}</li>
 *   <li>{@link fr.inria.diverse.networkModelTest.Binding#getNodeB <em>Node B</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getBinding()
 * @model
 * @generated
 */
public interface Binding extends EObject
{
  /**
   * Returns the value of the '<em><b>Node A</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.networkModelTest.nodeA}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node A</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node A</em>' containment reference list.
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getBinding_NodeA()
   * @model containment="true"
   * @generated
   */
  EList<nodeA> getNodeA();

  /**
   * Returns the value of the '<em><b>Node B</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.networkModelTest.nodeB}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node B</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node B</em>' containment reference list.
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getBinding_NodeB()
   * @model containment="true"
   * @generated
   */
  EList<nodeB> getNodeB();

} // Binding
