/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.networkModelTest;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
