/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.networkModelTest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Link ID</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.networkModelTest.LinkID#getLinkID <em>Link ID</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getLinkID()
 * @model
 * @generated
 */
public interface LinkID extends EObject
{
  /**
   * Returns the value of the '<em><b>Link ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Link ID</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link ID</em>' attribute.
   * @see #setLinkID(String)
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getLinkID_LinkID()
   * @model
   * @generated
   */
  String getLinkID();

  /**
   * Sets the value of the '{@link fr.inria.diverse.networkModelTest.LinkID#getLinkID <em>Link ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link ID</em>' attribute.
   * @see #getLinkID()
   * @generated
   */
  void setLinkID(String value);

} // LinkID
