/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.networkModelTest;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.networkModelTest.Model#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.networkModelTest.NodeElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getModel_Elements()
   * @model containment="true"
   * @generated
   */
  EList<NodeElement> getElements();

} // Model
