/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.networkModelTest;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.inria.diverse.networkModelTest.NetworkModelTestFactory
 * @model kind="package"
 * @generated
 */
public interface NetworkModelTestPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "networkModelTest";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.inria.fr/diverse/NetworkModelTest";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "networkModelTest";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  NetworkModelTestPackage eINSTANCE = fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.inria.diverse.networkModelTest.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.inria.diverse.networkModelTest.impl.ModelImpl
   * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.inria.diverse.networkModelTest.impl.NodeElementImpl <em>Node Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.inria.diverse.networkModelTest.impl.NodeElementImpl
   * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getNodeElement()
   * @generated
   */
  int NODE_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Node Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.inria.diverse.networkModelTest.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.inria.diverse.networkModelTest.impl.PackageDeclarationImpl
   * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getPackageDeclaration()
   * @generated
   */
  int PACKAGE_DECLARATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION__NAME = NODE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION__ELEMENTS = NODE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Package Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION_FEATURE_COUNT = NODE_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.inria.diverse.networkModelTest.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.inria.diverse.networkModelTest.impl.ImportImpl
   * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 3;

  /**
   * The feature id for the '<em><b>Imported Name Space</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORTED_NAME_SPACE = NODE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = NODE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.inria.diverse.networkModelTest.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.inria.diverse.networkModelTest.impl.TypeImpl
   * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getType()
   * @generated
   */
  int TYPE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = NODE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = NODE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.inria.diverse.networkModelTest.impl.DataTypeImpl <em>Data Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.inria.diverse.networkModelTest.impl.DataTypeImpl
   * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getDataType()
   * @generated
   */
  int DATA_TYPE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Data Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.inria.diverse.networkModelTest.impl.ConfigImpl <em>Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.inria.diverse.networkModelTest.impl.ConfigImpl
   * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getConfig()
   * @generated
   */
  int CONFIG = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__SUPER_TYPE = TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Node</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__NODE = TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Binding</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__BINDING = TYPE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_FEATURE_COUNT = TYPE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link fr.inria.diverse.networkModelTest.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.inria.diverse.networkModelTest.impl.NodeImpl
   * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getNode()
   * @generated
   */
  int NODE = 7;

  /**
   * The feature id for the '<em><b>Nodetype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NODETYPE = 0;

  /**
   * The feature id for the '<em><b>Node</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NODE = 1;

  /**
   * The feature id for the '<em><b>Image</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__IMAGE = 2;

  /**
   * The feature id for the '<em><b>Node Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NODE_NAME = 3;

  /**
   * The feature id for the '<em><b>Node ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NODE_ID = 4;

  /**
   * The feature id for the '<em><b>Node IP</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NODE_IP = 5;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link fr.inria.diverse.networkModelTest.impl.NodeTypeImpl <em>Node Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.inria.diverse.networkModelTest.impl.NodeTypeImpl
   * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getNodeType()
   * @generated
   */
  int NODE_TYPE = 8;

  /**
   * The feature id for the '<em><b>Nodetype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_TYPE__NODETYPE = 0;

  /**
   * The number of structural features of the '<em>Node Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.inria.diverse.networkModelTest.impl.BindingImpl <em>Binding</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.inria.diverse.networkModelTest.impl.BindingImpl
   * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getBinding()
   * @generated
   */
  int BINDING = 9;

  /**
   * The feature id for the '<em><b>Node A</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING__NODE_A = 0;

  /**
   * The feature id for the '<em><b>Node B</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING__NODE_B = 1;

  /**
   * The number of structural features of the '<em>Binding</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.inria.diverse.networkModelTest.impl.nodeAImpl <em>node A</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.inria.diverse.networkModelTest.impl.nodeAImpl
   * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getnodeA()
   * @generated
   */
  int NODE_A = 10;

  /**
   * The feature id for the '<em><b>Node</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_A__NODE = 0;

  /**
   * The feature id for the '<em><b>Eth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_A__ETH = 1;

  /**
   * The number of structural features of the '<em>node A</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_A_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.inria.diverse.networkModelTest.impl.nodeBImpl <em>node B</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.inria.diverse.networkModelTest.impl.nodeBImpl
   * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getnodeB()
   * @generated
   */
  int NODE_B = 11;

  /**
   * The feature id for the '<em><b>Node</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_B__NODE = 0;

  /**
   * The feature id for the '<em><b>Eth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_B__ETH = 1;

  /**
   * The number of structural features of the '<em>node B</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_B_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link fr.inria.diverse.networkModelTest.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see fr.inria.diverse.networkModelTest.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link fr.inria.diverse.networkModelTest.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see fr.inria.diverse.networkModelTest.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link fr.inria.diverse.networkModelTest.NodeElement <em>Node Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node Element</em>'.
   * @see fr.inria.diverse.networkModelTest.NodeElement
   * @generated
   */
  EClass getNodeElement();

  /**
   * Returns the meta object for class '{@link fr.inria.diverse.networkModelTest.PackageDeclaration <em>Package Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package Declaration</em>'.
   * @see fr.inria.diverse.networkModelTest.PackageDeclaration
   * @generated
   */
  EClass getPackageDeclaration();

  /**
   * Returns the meta object for the attribute '{@link fr.inria.diverse.networkModelTest.PackageDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.inria.diverse.networkModelTest.PackageDeclaration#getName()
   * @see #getPackageDeclaration()
   * @generated
   */
  EAttribute getPackageDeclaration_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.inria.diverse.networkModelTest.PackageDeclaration#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see fr.inria.diverse.networkModelTest.PackageDeclaration#getElements()
   * @see #getPackageDeclaration()
   * @generated
   */
  EReference getPackageDeclaration_Elements();

  /**
   * Returns the meta object for class '{@link fr.inria.diverse.networkModelTest.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see fr.inria.diverse.networkModelTest.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link fr.inria.diverse.networkModelTest.Import#getImportedNameSpace <em>Imported Name Space</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imported Name Space</em>'.
   * @see fr.inria.diverse.networkModelTest.Import#getImportedNameSpace()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportedNameSpace();

  /**
   * Returns the meta object for class '{@link fr.inria.diverse.networkModelTest.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see fr.inria.diverse.networkModelTest.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link fr.inria.diverse.networkModelTest.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.inria.diverse.networkModelTest.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for class '{@link fr.inria.diverse.networkModelTest.DataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Type</em>'.
   * @see fr.inria.diverse.networkModelTest.DataType
   * @generated
   */
  EClass getDataType();

  /**
   * Returns the meta object for class '{@link fr.inria.diverse.networkModelTest.Config <em>Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Config</em>'.
   * @see fr.inria.diverse.networkModelTest.Config
   * @generated
   */
  EClass getConfig();

  /**
   * Returns the meta object for the reference '{@link fr.inria.diverse.networkModelTest.Config#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see fr.inria.diverse.networkModelTest.Config#getSuperType()
   * @see #getConfig()
   * @generated
   */
  EReference getConfig_SuperType();

  /**
   * Returns the meta object for the containment reference list '{@link fr.inria.diverse.networkModelTest.Config#getNode <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Node</em>'.
   * @see fr.inria.diverse.networkModelTest.Config#getNode()
   * @see #getConfig()
   * @generated
   */
  EReference getConfig_Node();

  /**
   * Returns the meta object for the containment reference list '{@link fr.inria.diverse.networkModelTest.Config#getBinding <em>Binding</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Binding</em>'.
   * @see fr.inria.diverse.networkModelTest.Config#getBinding()
   * @see #getConfig()
   * @generated
   */
  EReference getConfig_Binding();

  /**
   * Returns the meta object for class '{@link fr.inria.diverse.networkModelTest.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see fr.inria.diverse.networkModelTest.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for the containment reference '{@link fr.inria.diverse.networkModelTest.Node#getNodetype <em>Nodetype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nodetype</em>'.
   * @see fr.inria.diverse.networkModelTest.Node#getNodetype()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Nodetype();

  /**
   * Returns the meta object for the attribute '{@link fr.inria.diverse.networkModelTest.Node#getNode <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Node</em>'.
   * @see fr.inria.diverse.networkModelTest.Node#getNode()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Node();

  /**
   * Returns the meta object for the attribute '{@link fr.inria.diverse.networkModelTest.Node#getImage <em>Image</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Image</em>'.
   * @see fr.inria.diverse.networkModelTest.Node#getImage()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Image();

  /**
   * Returns the meta object for the attribute '{@link fr.inria.diverse.networkModelTest.Node#getNodeName <em>Node Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Node Name</em>'.
   * @see fr.inria.diverse.networkModelTest.Node#getNodeName()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_NodeName();

  /**
   * Returns the meta object for the attribute '{@link fr.inria.diverse.networkModelTest.Node#getNodeID <em>Node ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Node ID</em>'.
   * @see fr.inria.diverse.networkModelTest.Node#getNodeID()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_NodeID();

  /**
   * Returns the meta object for the attribute '{@link fr.inria.diverse.networkModelTest.Node#getNodeIP <em>Node IP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Node IP</em>'.
   * @see fr.inria.diverse.networkModelTest.Node#getNodeIP()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_NodeIP();

  /**
   * Returns the meta object for class '{@link fr.inria.diverse.networkModelTest.NodeType <em>Node Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node Type</em>'.
   * @see fr.inria.diverse.networkModelTest.NodeType
   * @generated
   */
  EClass getNodeType();

  /**
   * Returns the meta object for the attribute '{@link fr.inria.diverse.networkModelTest.NodeType#getNodetype <em>Nodetype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nodetype</em>'.
   * @see fr.inria.diverse.networkModelTest.NodeType#getNodetype()
   * @see #getNodeType()
   * @generated
   */
  EAttribute getNodeType_Nodetype();

  /**
   * Returns the meta object for class '{@link fr.inria.diverse.networkModelTest.Binding <em>Binding</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Binding</em>'.
   * @see fr.inria.diverse.networkModelTest.Binding
   * @generated
   */
  EClass getBinding();

  /**
   * Returns the meta object for the containment reference list '{@link fr.inria.diverse.networkModelTest.Binding#getNodeA <em>Node A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Node A</em>'.
   * @see fr.inria.diverse.networkModelTest.Binding#getNodeA()
   * @see #getBinding()
   * @generated
   */
  EReference getBinding_NodeA();

  /**
   * Returns the meta object for the containment reference list '{@link fr.inria.diverse.networkModelTest.Binding#getNodeB <em>Node B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Node B</em>'.
   * @see fr.inria.diverse.networkModelTest.Binding#getNodeB()
   * @see #getBinding()
   * @generated
   */
  EReference getBinding_NodeB();

  /**
   * Returns the meta object for class '{@link fr.inria.diverse.networkModelTest.nodeA <em>node A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>node A</em>'.
   * @see fr.inria.diverse.networkModelTest.nodeA
   * @generated
   */
  EClass getnodeA();

  /**
   * Returns the meta object for the attribute '{@link fr.inria.diverse.networkModelTest.nodeA#getNode <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Node</em>'.
   * @see fr.inria.diverse.networkModelTest.nodeA#getNode()
   * @see #getnodeA()
   * @generated
   */
  EAttribute getnodeA_Node();

  /**
   * Returns the meta object for the attribute '{@link fr.inria.diverse.networkModelTest.nodeA#getEth <em>Eth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Eth</em>'.
   * @see fr.inria.diverse.networkModelTest.nodeA#getEth()
   * @see #getnodeA()
   * @generated
   */
  EAttribute getnodeA_Eth();

  /**
   * Returns the meta object for class '{@link fr.inria.diverse.networkModelTest.nodeB <em>node B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>node B</em>'.
   * @see fr.inria.diverse.networkModelTest.nodeB
   * @generated
   */
  EClass getnodeB();

  /**
   * Returns the meta object for the attribute '{@link fr.inria.diverse.networkModelTest.nodeB#getNode <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Node</em>'.
   * @see fr.inria.diverse.networkModelTest.nodeB#getNode()
   * @see #getnodeB()
   * @generated
   */
  EAttribute getnodeB_Node();

  /**
   * Returns the meta object for the attribute '{@link fr.inria.diverse.networkModelTest.nodeB#getEth <em>Eth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Eth</em>'.
   * @see fr.inria.diverse.networkModelTest.nodeB#getEth()
   * @see #getnodeB()
   * @generated
   */
  EAttribute getnodeB_Eth();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  NetworkModelTestFactory getNetworkModelTestFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.inria.diverse.networkModelTest.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.inria.diverse.networkModelTest.impl.ModelImpl
     * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link fr.inria.diverse.networkModelTest.impl.NodeElementImpl <em>Node Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.inria.diverse.networkModelTest.impl.NodeElementImpl
     * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getNodeElement()
     * @generated
     */
    EClass NODE_ELEMENT = eINSTANCE.getNodeElement();

    /**
     * The meta object literal for the '{@link fr.inria.diverse.networkModelTest.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.inria.diverse.networkModelTest.impl.PackageDeclarationImpl
     * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getPackageDeclaration()
     * @generated
     */
    EClass PACKAGE_DECLARATION = eINSTANCE.getPackageDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE_DECLARATION__NAME = eINSTANCE.getPackageDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE_DECLARATION__ELEMENTS = eINSTANCE.getPackageDeclaration_Elements();

    /**
     * The meta object literal for the '{@link fr.inria.diverse.networkModelTest.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.inria.diverse.networkModelTest.impl.ImportImpl
     * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Imported Name Space</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORTED_NAME_SPACE = eINSTANCE.getImport_ImportedNameSpace();

    /**
     * The meta object literal for the '{@link fr.inria.diverse.networkModelTest.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.inria.diverse.networkModelTest.impl.TypeImpl
     * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '{@link fr.inria.diverse.networkModelTest.impl.DataTypeImpl <em>Data Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.inria.diverse.networkModelTest.impl.DataTypeImpl
     * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getDataType()
     * @generated
     */
    EClass DATA_TYPE = eINSTANCE.getDataType();

    /**
     * The meta object literal for the '{@link fr.inria.diverse.networkModelTest.impl.ConfigImpl <em>Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.inria.diverse.networkModelTest.impl.ConfigImpl
     * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getConfig()
     * @generated
     */
    EClass CONFIG = eINSTANCE.getConfig();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG__SUPER_TYPE = eINSTANCE.getConfig_SuperType();

    /**
     * The meta object literal for the '<em><b>Node</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG__NODE = eINSTANCE.getConfig_Node();

    /**
     * The meta object literal for the '<em><b>Binding</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG__BINDING = eINSTANCE.getConfig_Binding();

    /**
     * The meta object literal for the '{@link fr.inria.diverse.networkModelTest.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.inria.diverse.networkModelTest.impl.NodeImpl
     * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '<em><b>Nodetype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__NODETYPE = eINSTANCE.getNode_Nodetype();

    /**
     * The meta object literal for the '<em><b>Node</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__NODE = eINSTANCE.getNode_Node();

    /**
     * The meta object literal for the '<em><b>Image</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__IMAGE = eINSTANCE.getNode_Image();

    /**
     * The meta object literal for the '<em><b>Node Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__NODE_NAME = eINSTANCE.getNode_NodeName();

    /**
     * The meta object literal for the '<em><b>Node ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__NODE_ID = eINSTANCE.getNode_NodeID();

    /**
     * The meta object literal for the '<em><b>Node IP</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__NODE_IP = eINSTANCE.getNode_NodeIP();

    /**
     * The meta object literal for the '{@link fr.inria.diverse.networkModelTest.impl.NodeTypeImpl <em>Node Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.inria.diverse.networkModelTest.impl.NodeTypeImpl
     * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getNodeType()
     * @generated
     */
    EClass NODE_TYPE = eINSTANCE.getNodeType();

    /**
     * The meta object literal for the '<em><b>Nodetype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE_TYPE__NODETYPE = eINSTANCE.getNodeType_Nodetype();

    /**
     * The meta object literal for the '{@link fr.inria.diverse.networkModelTest.impl.BindingImpl <em>Binding</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.inria.diverse.networkModelTest.impl.BindingImpl
     * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getBinding()
     * @generated
     */
    EClass BINDING = eINSTANCE.getBinding();

    /**
     * The meta object literal for the '<em><b>Node A</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINDING__NODE_A = eINSTANCE.getBinding_NodeA();

    /**
     * The meta object literal for the '<em><b>Node B</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINDING__NODE_B = eINSTANCE.getBinding_NodeB();

    /**
     * The meta object literal for the '{@link fr.inria.diverse.networkModelTest.impl.nodeAImpl <em>node A</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.inria.diverse.networkModelTest.impl.nodeAImpl
     * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getnodeA()
     * @generated
     */
    EClass NODE_A = eINSTANCE.getnodeA();

    /**
     * The meta object literal for the '<em><b>Node</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE_A__NODE = eINSTANCE.getnodeA_Node();

    /**
     * The meta object literal for the '<em><b>Eth</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE_A__ETH = eINSTANCE.getnodeA_Eth();

    /**
     * The meta object literal for the '{@link fr.inria.diverse.networkModelTest.impl.nodeBImpl <em>node B</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.inria.diverse.networkModelTest.impl.nodeBImpl
     * @see fr.inria.diverse.networkModelTest.impl.NetworkModelTestPackageImpl#getnodeB()
     * @generated
     */
    EClass NODE_B = eINSTANCE.getnodeB();

    /**
     * The meta object literal for the '<em><b>Node</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE_B__NODE = eINSTANCE.getnodeB_Node();

    /**
     * The meta object literal for the '<em><b>Eth</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE_B__ETH = eINSTANCE.getnodeB_Eth();

  }

} //NetworkModelTestPackage
