/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.networkModelTest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>node A</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.networkModelTest.nodeA#getNode <em>Node</em>}</li>
 *   <li>{@link fr.inria.diverse.networkModelTest.nodeA#getEth <em>Eth</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getnodeA()
 * @model
 * @generated
 */
public interface nodeA extends EObject
{
  /**
   * Returns the value of the '<em><b>Node</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node</em>' attribute.
   * @see #setNode(String)
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getnodeA_Node()
   * @model
   * @generated
   */
  String getNode();

  /**
   * Sets the value of the '{@link fr.inria.diverse.networkModelTest.nodeA#getNode <em>Node</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node</em>' attribute.
   * @see #getNode()
   * @generated
   */
  void setNode(String value);

  /**
   * Returns the value of the '<em><b>Eth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Eth</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eth</em>' attribute.
   * @see #setEth(String)
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getnodeA_Eth()
   * @model
   * @generated
   */
  String getEth();

  /**
   * Sets the value of the '{@link fr.inria.diverse.networkModelTest.nodeA#getEth <em>Eth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eth</em>' attribute.
   * @see #getEth()
   * @generated
   */
  void setEth(String value);

} // nodeA
