/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.networkModelTest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNodeElement()
 * @model
 * @generated
 */
public interface NodeElement extends EObject
{
} // NodeElement
