/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.networkModelTest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.networkModelTest.NodeType#getNodetype <em>Nodetype</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNodeType()
 * @model
 * @generated
 */
public interface NodeType extends EObject
{
  /**
   * Returns the value of the '<em><b>Nodetype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nodetype</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodetype</em>' attribute.
   * @see #setNodetype(String)
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNodeType_Nodetype()
   * @model
   * @generated
   */
  String getNodetype();

  /**
   * Sets the value of the '{@link fr.inria.diverse.networkModelTest.NodeType#getNodetype <em>Nodetype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nodetype</em>' attribute.
   * @see #getNodetype()
   * @generated
   */
  void setNodetype(String value);

} // NodeType
