/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.networkModelTest;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.networkModelTest.Node#getNodetype <em>Nodetype</em>}</li>
 *   <li>{@link fr.inria.diverse.networkModelTest.Node#getNode <em>Node</em>}</li>
 *   <li>{@link fr.inria.diverse.networkModelTest.Node#getImage <em>Image</em>}</li>
 *   <li>{@link fr.inria.diverse.networkModelTest.Node#getNodeName <em>Node Name</em>}</li>
 *   <li>{@link fr.inria.diverse.networkModelTest.Node#getNodeID <em>Node ID</em>}</li>
 *   <li>{@link fr.inria.diverse.networkModelTest.Node#getNodeIP <em>Node IP</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNode()
 * @model
 * @generated
 */
public interface Node extends EObject
{
  /**
   * Returns the value of the '<em><b>Nodetype</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.networkModelTest.NodeType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nodetype</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodetype</em>' containment reference list.
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNode_Nodetype()
   * @model containment="true"
   * @generated
   */
  EList<NodeType> getNodetype();

  /**
   * Returns the value of the '<em><b>Node</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node</em>' attribute.
   * @see #setNode(String)
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNode_Node()
   * @model
   * @generated
   */
  String getNode();

  /**
   * Sets the value of the '{@link fr.inria.diverse.networkModelTest.Node#getNode <em>Node</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node</em>' attribute.
   * @see #getNode()
   * @generated
   */
  void setNode(String value);

  /**
   * Returns the value of the '<em><b>Image</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Image</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Image</em>' attribute.
   * @see #setImage(String)
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNode_Image()
   * @model
   * @generated
   */
  String getImage();

  /**
   * Sets the value of the '{@link fr.inria.diverse.networkModelTest.Node#getImage <em>Image</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Image</em>' attribute.
   * @see #getImage()
   * @generated
   */
  void setImage(String value);

  /**
   * Returns the value of the '<em><b>Node Name</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node Name</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node Name</em>' attribute list.
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNode_NodeName()
   * @model unique="false"
   * @generated
   */
  EList<String> getNodeName();

  /**
   * Returns the value of the '<em><b>Node ID</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node ID</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node ID</em>' attribute list.
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNode_NodeID()
   * @model unique="false"
   * @generated
   */
  EList<String> getNodeID();

  /**
   * Returns the value of the '<em><b>Node IP</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node IP</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node IP</em>' attribute list.
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNode_NodeIP()
   * @model unique="false"
   * @generated
   */
  EList<String> getNodeIP();

} // Node
