/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.networkModelTest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.networkModelTest.Node#getNodetype <em>Nodetype</em>}</li>
 *   <li>{@link fr.inria.diverse.networkModelTest.Node#getNode <em>Node</em>}</li>
 *   <li>{@link fr.inria.diverse.networkModelTest.Node#getImage <em>Image</em>}</li>
 *   <li>{@link fr.inria.diverse.networkModelTest.Node#getNodeName <em>Node Name</em>}</li>
 *   <li>{@link fr.inria.diverse.networkModelTest.Node#getNodeID <em>Node ID</em>}</li>
 *   <li>{@link fr.inria.diverse.networkModelTest.Node#getNodeIP <em>Node IP</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNode()
 * @model
 * @generated
 */
public interface Node extends EObject
{
  /**
   * Returns the value of the '<em><b>Nodetype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nodetype</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodetype</em>' containment reference.
   * @see #setNodetype(NodeType)
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNode_Nodetype()
   * @model containment="true"
   * @generated
   */
  NodeType getNodetype();

  /**
   * Sets the value of the '{@link fr.inria.diverse.networkModelTest.Node#getNodetype <em>Nodetype</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nodetype</em>' containment reference.
   * @see #getNodetype()
   * @generated
   */
  void setNodetype(NodeType value);

  /**
   * Returns the value of the '<em><b>Node</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node</em>' attribute.
   * @see #setNode(String)
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNode_Node()
   * @model
   * @generated
   */
  String getNode();

  /**
   * Sets the value of the '{@link fr.inria.diverse.networkModelTest.Node#getNode <em>Node</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node</em>' attribute.
   * @see #getNode()
   * @generated
   */
  void setNode(String value);

  /**
   * Returns the value of the '<em><b>Image</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Image</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Image</em>' attribute.
   * @see #setImage(String)
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNode_Image()
   * @model
   * @generated
   */
  String getImage();

  /**
   * Sets the value of the '{@link fr.inria.diverse.networkModelTest.Node#getImage <em>Image</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Image</em>' attribute.
   * @see #getImage()
   * @generated
   */
  void setImage(String value);

  /**
   * Returns the value of the '<em><b>Node Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node Name</em>' attribute.
   * @see #setNodeName(String)
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNode_NodeName()
   * @model
   * @generated
   */
  String getNodeName();

  /**
   * Sets the value of the '{@link fr.inria.diverse.networkModelTest.Node#getNodeName <em>Node Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node Name</em>' attribute.
   * @see #getNodeName()
   * @generated
   */
  void setNodeName(String value);

  /**
   * Returns the value of the '<em><b>Node ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node ID</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node ID</em>' attribute.
   * @see #setNodeID(String)
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNode_NodeID()
   * @model
   * @generated
   */
  String getNodeID();

  /**
   * Sets the value of the '{@link fr.inria.diverse.networkModelTest.Node#getNodeID <em>Node ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node ID</em>' attribute.
   * @see #getNodeID()
   * @generated
   */
  void setNodeID(String value);

  /**
   * Returns the value of the '<em><b>Node IP</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node IP</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node IP</em>' attribute.
   * @see #setNodeIP(String)
   * @see fr.inria.diverse.networkModelTest.NetworkModelTestPackage#getNode_NodeIP()
   * @model
   * @generated
   */
  String getNodeIP();

  /**
   * Sets the value of the '{@link fr.inria.diverse.networkModelTest.Node#getNodeIP <em>Node IP</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node IP</em>' attribute.
   * @see #getNodeIP()
   * @generated
   */
  void setNodeIP(String value);

} // Node
