/**
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.ui.contentassist;

import fr.inria.diverse.ui.contentassist.AbstractNetworkModelTestProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class NetworkModelTestProposalProvider extends AbstractNetworkModelTestProposalProvider {
}
