/*
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractNetworkModelTestScopeProvider extends DelegatingScopeProvider {
}
