/*
 * generated by Xtext 2.16.0
 */
package fr.inria.diverse.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractNetworkModelTestValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(fr.inria.diverse.networkModelTest.NetworkModelTestPackage.eINSTANCE);
		return result;
	}
}
